### ISSUE TITLE
Embed Doesn't work with Rom URLs in new google sites

### ISSUE THREAD

**Issue by 69xxx69lol** [ethanaobrien/emulatorjs#61]
The embeds are just blank and If it somehow works only text is displayed in the box or it will have the play now button, attempt to load and download the rom and fail.

**Comment by ethanaobrien** [comment]
You cannot embed this in google sites, it does not support custom html code

**Comment by allancoding** [comment]
You could try embedding this in google sites: [https://allancoding.github.io/emulatorjs/](https://allancoding.github.io/emulatorjs/)
Just upload the zip or the rom and then copy the generated link and put that in google sites.

**Comment by 69xxx69lol** [comment]
> You could try embedding this in google sites: https://allancoding.github.io/emulatorjs/ Just upload the zip or the rom and then copy the generated link and put that in google sites.

Doesn't exactly help the way I wanted it to but it helps a lot.
thank you.

**Comment by 69xxx69lol** [comment]
problem is that I'm using git to host the rom file and I need to use somewhere else to host since it doesn't seem to accept roms from the git url

I did something similar with a ruffle embed but it actually worked with the urls
