### ISSUE TITLE
Firefox: `TypeError: navigator.getGamepads is not a function`

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [ethanaobrien/emulatorjs#84]
Traceback:

![image](https://user-images.githubusercontent.com/65097669/148661870-d3e969b4-c0fc-4aaa-a46b-3bcbdaf43768.png)

The exact same setup works on Chrome.
Core: `gba`
Game: A pokemon Fire Red GBA
Bios: Bios provided by [emulation wiki](https://emulation.gametechwiki.com/index.php/Emulator_files#Game_Boy_Advance_.2F_e-Reader)

All of my gamepad settings are the default (about:config)
![image](https://user-images.githubusercontent.com/65097669/148661956-fbdad18e-0e73-4018-af38-86f07a0ee25f.png)

**Comment by ethanaobrien** [comment]
@FoxNerdSaysMoo What os are you using?

**Comment by FoxNerdSaysMoo** [comment]
Arch Linux

**Comment by FoxNerdSaysMoo** [comment]
This also occurs with a tetris worlds gba file.
SNES games still work perfectly though.

**Comment by FoxNerdSaysMoo** [comment]
This is using the latest version of this repo (as of yesterday)

**Comment by ethanaobrien** [comment]
Awesome, thank you, I'll take a look at this

**Comment by FoxNerdSaysMoo** [comment]
This is now working as intended (as far as I can tell).

**Comment by ethanaobrien** [comment]
If this seems to happen again, please reopen (as I changed nothing) It couldve been a bug in the browser though.

Thank you
